# Pieces 0-indexed by last number; provided the colour
# and type are correct, which piece is assigned to
# which field can be arbitrary.

geometry_msgs/Pose w_pawn_0
geometry_msgs/Pose w_pawn_1
geometry_msgs/Pose w_pawn_2
geometry_msgs/Pose w_pawn_3
geometry_msgs/Pose w_pawn_4
geometry_msgs/Pose w_pawn_5
geometry_msgs/Pose w_pawn_6
geometry_msgs/Pose w_pawn_7
geometry_msgs/Pose w_rook_0
geometry_msgs/Pose w_knight_0
geometry_msgs/Pose w_bishop_0
geometry_msgs/Pose w_queen
geometry_msgs/Pose w_king
geometry_msgs/Pose w_bishop_1
geometry_msgs/Pose w_knight_1
geometry_msgs/Pose w_rook_1

geometry_msgs/Pose b_pawn_0
geometry_msgs/Pose b_pawn_1
geometry_msgs/Pose b_pawn_2
geometry_msgs/Pose b_pawn_3
geometry_msgs/Pose b_pawn_4
geometry_msgs/Pose b_pawn_5
geometry_msgs/Pose b_pawn_6
geometry_msgs/Pose b_pawn_7
geometry_msgs/Pose b_rook_0
geometry_msgs/Pose b_knight_0
geometry_msgs/Pose b_bishop_0
geometry_msgs/Pose b_queen
geometry_msgs/Pose b_king
geometry_msgs/Pose b_bishop_1
geometry_msgs/Pose b_knight_1
geometry_msgs/Pose b_rook_1
