uint8 W_PAWN_0 = 0
uint8 W_PAWN_1 = 1
uint8 W_PAWN_2 = 2
uint8 W_PAWN_3 = 3
uint8 W_PAWN_4 = 4
uint8 W_PAWN_5 = 5
uint8 W_PAWN_6 = 6
uint8 W_PAWN_7 = 7
uint8 W_ROOK_0 = 8
uint8 W_KNIGHT_0 = 9
uint8 W_BISHOP_0 = 10
uint8 W_QUEEN = 11
uint8 W_KING = 12
uint8 W_BISHOP_1 = 13
uint8 W_KNIGHT_1 = 14
uint8 W_ROOK_1 = 15

uint8 B_PAWN_0 = 16
uint8 B_PAWN_1 = 17
uint8 B_PAWN_2 = 18
uint8 B_PAWN_3 = 19
uint8 B_PAWN_4 = 20
uint8 B_PAWN_5 = 21
uint8 B_PAWN_6 = 22
uint8 B_PAWN_7 = 23
uint8 B_ROOK_0 = 24
uint8 B_KNIGHT_0 = 25
uint8 B_BISHOP_0 = 26
uint8 B_QUEEN = 27
uint8 B_KING = 28
uint8 B_BISHOP_1 = 29
uint8 B_KNIGHT_1 = 30
uint8 B_ROOK_1 = 31

uint8 piece_name
