# Pieces 0-indexed by last number; provided the colour
# and type are correct, which piece is assigned to
# which field can be arbitrary.

Pose w_pawn_0
Pose w_pawn_1
Pose w_pawn_2
Pose w_pawn_3
Pose w_pawn_4
Pose w_pawn_5
Pose w_pawn_6
Pose w_pawn_7
Pose w_rook_0
Pose w_knight_0
Pose w_bishop_0
Pose w_queen
Pose w_king
Pose w_bishop_1
Pose w_knight_1
Pose w_rook_1

Pose b_pawn_0
Pose b_pawn_1
Pose b_pawn_2
Pose b_pawn_3
Pose b_pawn_4
Pose b_pawn_5
Pose b_pawn_6
Pose b_pawn_7
Pose b_rook_0
Pose b_knight_0
Pose b_bishop_0
Pose b_queen
Pose b_king
Pose b_bishop_1
Pose b_knight_1
Pose b_rook_1
