# Pieces 0-indexed by last number; provided the colour
# and type are correct, which piece is assigned to
# which field can be arbitrary.

Square w_pawn_0
Square w_pawn_1
Square w_pawn_2
Square w_pawn_3
Square w_pawn_4
Square w_pawn_5
Square w_pawn_6
Square w_pawn_7
Square w_rook_0
Square w_knight_0
Square w_bishop_0
Square w_queen
Square w_king
Square w_bishop_1
Square w_knight_1
Square w_rook_1

Square b_pawn_0
Square b_pawn_1
Square b_pawn_2
Square b_pawn_3
Square b_pawn_4
Square b_pawn_5
Square b_pawn_6
Square b_pawn_7
Square b_rook_0
Square b_knight_0
Square b_bishop_0
Square b_queen
Square b_king
Square b_bishop_1
Square b_knight_1
Square b_rook_1
